In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the dataset into python environment

In [2]:
data = pd.read_csv(r'C:\Users\user\Downloads\titanic_dataset.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

# 2. Make ‘PassengerId’ as the index column

In [4]:
data.set_index('PassengerId', inplace=True)

# 3. Check the basic details of the dataset

In [5]:
data.shape

(891, 11)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Name      891 non-null    object 
 3   Sex       891 non-null    object 
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64  
 6   Parch     891 non-null    int64  
 7   Ticket    891 non-null    object 
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object 
 10  Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB


In [7]:
data.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# 4. Drop the unnecessary columns

In [8]:
data = data.drop(['Name', 'Ticket', 'Cabin'], axis=1)

In [9]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

# 5. Handle the missing values (if any)

In [10]:
data.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [11]:
for column in ['Age', 'Embarked']:
    if column == 'Age':
        data[column] = data[column].fillna(data[column].mean())
    elif column == 'Embarked':
        data[column] = data[column].fillna(data[column].mode()[0])

In [12]:
data.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# 6. Perform Encoding

In [13]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

In [14]:
columns_to_encode = ['Sex', 'Embarked']

In [15]:
data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [16]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
PassengerId                                                              
1                   0       3  1.0  22.0      1      0   7.2500       2.0
2                   1       1  0.0  38.0      1      0  71.2833       0.0
3                   1       3  0.0  26.0      0      0   7.9250       2.0
4                   1       1  0.0  35.0      1      0  53.1000       2.0
5                   0       3  1.0  35.0      0      0   8.0500       2.0

In [17]:
data.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# 7. Split the target feature and perform Scaling

In [18]:
x = data.drop('Survived', axis=1)
y = data['Survived']

In [19]:
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler(feature_range = (0,1))
x = min_max.fit_transform(x)

In [20]:
type(x)

numpy.ndarray

In [21]:
x = pd.DataFrame(x)

In [22]:
x.head()

0    1         2      3    4         5    6
0  1.0  1.0  0.271174  0.125  0.0  0.014151  1.0
1  0.0  0.0  0.472229  0.125  0.0  0.139136  0.0
2  1.0  0.0  0.321438  0.000  0.0  0.015469  1.0
3  0.0  0.0  0.434531  0.125  0.0  0.103644  1.0
4  1.0  1.0  0.434531  0.000  0.0  0.015713  1.0

In [23]:
x.columns = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [24]:
x.head()

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0     1.0  1.0  0.271174  0.125    0.0  0.014151       1.0
1     0.0  0.0  0.472229  0.125    0.0  0.139136       0.0
2     1.0  0.0  0.321438  0.000    0.0  0.015469       1.0
3     0.0  0.0  0.434531  0.125    0.0  0.103644       1.0
4     1.0  1.0  0.434531  0.000    0.0  0.015713       1.0

In [25]:
y.head()

PassengerId
1    0
2    1
3    1
4    1
5    0
Name: Survived, dtype: int64

In [26]:
x.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

# 8. kNN with k-fold cross validation

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()

In [28]:
from sklearn.model_selection import KFold, cross_val_score
kfold_val = KFold(10)

In [29]:
for train_index, test_index in kfold_val.split(x,y):
    print('Training Index :', train_index)
    print('Testing Index : ', test_index)

Training Index : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 3

In [30]:
kfold_scores_knn = cross_val_score(knn_model, x, y, cv=kfold_val)
kfold_scores_knn

array([0.75555556, 0.82022472, 0.75280899, 0.7752809 , 0.85393258,
       0.80898876, 0.82022472, 0.7752809 , 0.85393258, 0.75280899])

In [31]:
average_accuracy_knn = kfold_scores_knn.mean()
average_accuracy_knn 

0.7969038701622971

# 9. kNN with Stratified k-fold cross validation

In [32]:
from sklearn.model_selection import StratifiedKFold
skfold_val = StratifiedKFold(n_splits =10)

In [33]:
for train_index, test_index in skfold_val.split(x,y):
    print('Training Index :', train_index)
    print('Testing Index : ', test_index)

Training Index : [ 82  84  85  88  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 3

In [34]:
skfold_scores_knn = cross_val_score(knn_model, x, y, cv=skfold_val)
skfold_scores_knn

array([0.75555556, 0.83146067, 0.71910112, 0.7752809 , 0.87640449,
       0.79775281, 0.84269663, 0.78651685, 0.82022472, 0.76404494])

In [35]:
average_accuracy_stratified_knn = skfold_scores_knn.mean()
average_accuracy_stratified_knn

0.7969038701622971

# 10. SVM with k-fold cross validation

In [36]:
from sklearn.svm import SVC
svm_model = SVC()

In [37]:
kfold_scores_svm = cross_val_score(svm_model, x, y, cv=kfold_val)
kfold_scores_svm

array([0.81111111, 0.84269663, 0.78651685, 0.82022472, 0.80898876,
       0.82022472, 0.78651685, 0.75280899, 0.85393258, 0.82022472])

In [38]:
average_accuracy_svm = kfold_scores_svm.mean()
average_accuracy_svm

0.8103245942571785

# 11. SVM with Stratified k-fold cross validation

In [39]:
skfold_scores_svm = cross_val_score(svm_model, x, y, cv=skfold_val)
skfold_scores_svm

array([0.82222222, 0.78651685, 0.78651685, 0.85393258, 0.84269663,
       0.79775281, 0.80898876, 0.76404494, 0.83146067, 0.80898876])

In [40]:
average_accuracy_stratified_svm = skfold_scores_svm.mean()
average_accuracy_stratified_svm

0.8103121098626715